#!/bin/bash

SCRIPT_FOLDER=$(dirname "$0")

. "${SCRIPT_FOLDER}/intellij_common"

checknode
setupsdk
licensing

cachemodules $@

copylibs

if [ "" == "$(which mvn)" ]; then
    "$NODEJS" "${SCRIPT_FOLDER}/bin/run.js" "$PWD" "$@" --no-tests=true
else
    "$NODEJS" "${SCRIPT_FOLDER}/bin/run.js" "$PWD" "$@" --mvn-cache=true --no-tests=true
fi

uncachemodules $@

ignoreiml

enabledebug